### ISSUE TITLE
Vue.ImagesLoaded And Vue.Isotope Doesnt Seem To Be Working For Me

### ISSUE THREAD

**Issue by BenQoder** [David-Desmaisons/Vue.ImagesLoaded#3]
Template Layout

`					<isotope v-images-loaded:on.progress="changeLayout()" :options="options" :list="cards">
					</isotope>	
`
Method

` 
		    changeLayout: function() {
		      this.$refs.cpt.layout('masonry');
		   	},
`

I Get  Error In Console 

`
Uncaught TypeError: Cannot read property 'layout' of undefined
    at VueComponent.changeLayout (app.js:53417)
    at boundFn (app.js:43233)
    at app.js:64187
changeLayout @ app.js:53417
boundFn @ app.js:43233
(anonymous) @ app.js:64187
setTimeout (async)
(anonymous) @ app.js:64187
e.emitEvent @ app.js:64187
o.progress @ app.js:64192
(anonymous) @ app.js:64192
setTimeout (async)
t @ app.js:64192
e.emitEvent @ app.js:64187
i.confirm @ app.js:64192
i.onload @ app.js:64192
i.handleEvent @ app.js:64192

`

**Comment by David-Desmaisons** [comment]
Did you check installation information [here](https://github.com/David-Desmaisons/Vue.Isotope#gotchas)?

**Comment by BenQoder** [comment]
I Did Set The Key Props Correctly

**Comment by David-Desmaisons** [comment]
could you share the vue file where you declare the component?
