### ISSUE TITLE
VueImagesLoaded Nuxt question

### ISSUE THREAD

**Issue by EnzoBatista** [David-Desmaisons/Vue.ImagesLoaded#8]
I'm tying to implement it in nuxt but i have  a "Failed to resolve directive: images-loaded" in console

**plugin**
```import Vue from 'vue'
import imagesLoaded from 'vue-images-loaded'
Vue.use('imagesLoaded', imagesLoaded)
```

who's linked in nuxt.config.js

**template**
```
<div v-images-loaded="loaded" class="item__img-box">
      <img :src="`img/articles/${ item.imageLink }`" class="" alt="Alternate text for the image">
  </div>
```

**Comment by David-Desmaisons** [comment]
Do not use this directive in node context. I think there is a way to mock directive in node context.

**Comment by EnzoBatista** [comment]
Could you give me an example please?

**Comment by David-Desmaisons** [comment]
=> https://ssr.vuejs.org/api/#directives

**Comment by EnzoBatista** [comment]
@David-Desmaisons Thank you dude!

**Comment by jillztom** [comment]
@EnzoBatista Can you share the solution?

**Comment by jillztom** [comment]
@David-Desmaisons can you provide an example for this SSR solution?

**Comment by andresclua** [comment]
any update on this? @jillztom @David-Desmaisons
